spring:
  shardingsphere:
    enabled: true
    datasource:
      names: db0,db1
      common:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
      db0:
        url: jdbc:mysql://127.0.0.1:3316/test
        username: root
        password: 123456
      db1:
        url: jdbc:mysql://127.0.0.1:3326/test
        username: root
        password: 123456



